apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: "go"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
