apiVersion: v1
kind: Service
metadata:
  name: go
spec:
  type: NodePort
  selector:
    app: go
  ports:
    - name: htpp
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
